public class HP_DoctorSOAPServiceHelper {
    public static String noRecordWithId = System.Label.NoRecordWithId;
    public static String noRecords = System.Label.NoRecords;
    public static String success = System.Label.SuccessOperation;
    public static String notComplete = 'Not complete operation';

    public static Integer ERROR = 0;
    public static Integer OK = 1;
    public static Integer WARN = 2;
}